name: google_ml_kit_example
description: "Demonstrates how to use the google_ml_kit plugin."

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  camera: ^0.11.1
  # The default Android implementation from camera_android_camerax doesn't support the required image format.
  camera_android: ^0.10.10+1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5


  # tflite_flutter_plus: ^0.0.1
  tflite_flutter:  0.11.0
  # tflite_flutter_helper: ^0.4.2
  # image: ^3.1.0

  google_mlkit_commons: ^0.11.0
  google_mlkit_pose_detection: ^0.14.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
